# Generated by Django 6.0.6 on 2026-06-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="cursos",
        ),
        migrations.AddField(
            model_name="curso",
            name="alunos",
            field=models.ManyToManyField(related_name="cursos", to="escola.aluno"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="numero",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="curso",
            name="imagem",
            field=models.ImageField(upload_to="cursos/"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
