# Generated by Django 6.0.6 on 2026-06-26 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.PositiveIntegerField(unique=True)),
                ("nome", models.CharField(max_length=255)),
                ("grau", models.CharField(blank=True, max_length=255)),
                (
                    "plano_curricular_codigo",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("plano_curricular_nome", models.CharField(blank=True, max_length=255)),
                ("area_cientifica", models.CharField(blank=True, max_length=255)),
                ("codigo_area_cientifica", models.CharField(blank=True, max_length=50)),
                ("cnaef", models.CharField(blank=True, max_length=50)),
                (
                    "ects",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("estado_acreditacao", models.CharField(blank=True, max_length=255)),
                (
                    "codigo_estado_acreditacao",
                    models.CharField(blank=True, max_length=50),
                ),
                ("data_publicacao", models.DateField(blank=True, null=True)),
                ("apresentacao", models.TextField(blank=True)),
                ("objetivos", models.TextField(blank=True)),
                ("saidas_profissionais", models.TextField(blank=True)),
                ("condicoes_acesso", models.TextField(blank=True)),
                ("estudos_futuros", models.TextField(blank=True)),
                ("contactos_direcao", models.CharField(blank=True, max_length=255)),
                ("email_direcao", models.EmailField(blank=True, max_length=254)),
                (
                    "contactos_secretariado",
                    models.CharField(blank=True, max_length=255),
                ),
                ("email_secretariado", models.EmailField(blank=True, max_length=254)),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_legivel", models.CharField(max_length=50, unique=True)),
                ("codigo", models.PositiveIntegerField()),
                ("nome", models.CharField(max_length=255)),
                ("ano", models.PositiveSmallIntegerField()),
                ("semestre", models.CharField(max_length=20)),
                ("semestre_codigo", models.CharField(max_length=10)),
                ("ects", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "grupo_codigo",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("grupo_nome", models.CharField(blank=True, max_length=255)),
                (
                    "ramo_codigo",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("ramo_nome", models.CharField(blank=True, max_length=255)),
                ("opcao_codigo", models.CharField(blank=True, max_length=10)),
                ("opcao", models.CharField(blank=True, max_length=100)),
                (
                    "horas_contacto",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "horas_contacto_int",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("mobilidade_entrada", models.BooleanField(default=False)),
                ("mobilidade_saida", models.BooleanField(default=False)),
                ("lingua", models.CharField(blank=True, max_length=20)),
                ("lingua_codigo", models.CharField(blank=True, max_length=20)),
                ("tipo", models.CharField(blank=True, max_length=100)),
                ("natureza", models.CharField(blank=True, max_length=100)),
                ("diploma", models.CharField(blank=True, max_length=255)),
                ("apresentacao", models.TextField(blank=True)),
                ("objetivos", models.TextField(blank=True)),
                ("programa", models.TextField(blank=True)),
                ("metodologia", models.TextField(blank=True)),
                ("avaliacao", models.TextField(blank=True)),
                ("bibliografia", models.TextField(blank=True)),
                ("competencias", models.TextField(blank=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_curriculares",
                        to="portfolio.curso",
                    ),
                ),
            ],
            options={
                "ordering": ("curso", "ano", "semestre", "nome"),
            },
        ),
    ]
