# Generated by Django 6.0.6 on 2026-06-26 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=160)),
                ("instituicao", models.CharField(max_length=160)),
                ("descricao", models.TextField(blank=True)),
                ("ano_inicio", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("ano_fim", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ("-ano_inicio", "nome"),
            },
        ),
        migrations.CreateModel(
            name="MakingOfEntrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("commit_hash", models.CharField(max_length=40)),
                ("iteracao", models.PositiveIntegerField()),
                ("titulo", models.CharField(max_length=160)),
                ("descricao", models.TextField()),
                ("alteracoes", models.TextField(blank=True)),
                ("dificuldades", models.TextField(blank=True)),
                ("resultado", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-data", "-iteracao"),
            },
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("descricao", models.TextField(blank=True)),
                ("vantagens", models.TextField(blank=True)),
                ("desvantagens", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ("tipo", "nome"),
            },
        ),
        migrations.CreateModel(
            name="TipoTecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=160)),
                ("resumo", models.CharField(blank=True, max_length=255)),
                ("descricao", models.TextField(blank=True)),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="portfolio/projetos/"
                    ),
                ),
                ("github_url", models.URLField(blank=True)),
                ("demo_url", models.URLField(blank=True)),
                ("data_criacao", models.DateField(auto_now_add=True)),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.competencia"
                    ),
                ),
                (
                    "formacoes",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.formacao"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
            ],
            options={
                "ordering": ("-data_criacao", "titulo"),
            },
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tecnologias",
                to="portfolio.tipotecnologia",
            ),
        ),
    ]
